package b.i.c.m.d.m;

/* JADX INFO: compiled from: AutoCrashlyticsReportEncoder.java */
/* JADX INFO: loaded from: classes3.dex */
public final class a implements b.i.c.p.g.a {
    public static final b.i.c.p.g.a a = new a();

    public void a(b.i.c.p.g.b<?> bVar) {
        a$b a_b = a$b.a;
        b.i.c.p.h.e eVar = (b.i.c.p.h.e) bVar;
        eVar.f1761b.put(v.class, a_b);
        eVar.c.remove(v.class);
        eVar.f1761b.put(b.class, a_b);
        eVar.c.remove(b.class);
        a$h a_h = a$h.a;
        eVar.f1761b.put(v$d.class, a_h);
        eVar.c.remove(v$d.class);
        eVar.f1761b.put(f.class, a_h);
        eVar.c.remove(f.class);
        a$e a_e = a$e.a;
        eVar.f1761b.put(v$d$a.class, a_e);
        eVar.c.remove(v$d$a.class);
        eVar.f1761b.put(g.class, a_e);
        eVar.c.remove(g.class);
        a$f a_f = a$f.a;
        eVar.f1761b.put(v$d$a$a.class, a_f);
        eVar.c.remove(v$d$a$a.class);
        eVar.f1761b.put(h.class, a_f);
        eVar.c.remove(h.class);
        a$t a_t = a$t.a;
        eVar.f1761b.put(v$d$f.class, a_t);
        eVar.c.remove(v$d$f.class);
        eVar.f1761b.put(u.class, a_t);
        eVar.c.remove(u.class);
        a$s a_s = a$s.a;
        eVar.f1761b.put(v$d$e.class, a_s);
        eVar.c.remove(v$d$e.class);
        eVar.f1761b.put(t.class, a_s);
        eVar.c.remove(t.class);
        a$g a_g = a$g.a;
        eVar.f1761b.put(v$d$c.class, a_g);
        eVar.c.remove(v$d$c.class);
        eVar.f1761b.put(i.class, a_g);
        eVar.c.remove(i.class);
        a$q a_q = a$q.a;
        eVar.f1761b.put(v$d$d.class, a_q);
        eVar.c.remove(v$d$d.class);
        eVar.f1761b.put(j.class, a_q);
        eVar.c.remove(j.class);
        a$i a_i = a$i.a;
        eVar.f1761b.put(v$d$d$a.class, a_i);
        eVar.c.remove(v$d$d$a.class);
        eVar.f1761b.put(k.class, a_i);
        eVar.c.remove(k.class);
        a$k a_k = a$k.a;
        eVar.f1761b.put(v$d$d$a$b.class, a_k);
        eVar.c.remove(v$d$d$a$b.class);
        eVar.f1761b.put(l.class, a_k);
        eVar.c.remove(l.class);
        a$n a_n = a$n.a;
        eVar.f1761b.put(v$d$d$a$b$d.class, a_n);
        eVar.c.remove(v$d$d$a$b$d.class);
        eVar.f1761b.put(p.class, a_n);
        eVar.c.remove(p.class);
        a$o a_o = a$o.a;
        eVar.f1761b.put(v$d$d$a$b$d$a.class, a_o);
        eVar.c.remove(v$d$d$a$b$d$a.class);
        eVar.f1761b.put(q.class, a_o);
        eVar.c.remove(q.class);
        a$l a_l = a$l.a;
        eVar.f1761b.put(v$d$d$a$b$b.class, a_l);
        eVar.c.remove(v$d$d$a$b$b.class);
        eVar.f1761b.put(n.class, a_l);
        eVar.c.remove(n.class);
        a$m a_m = a$m.a;
        eVar.f1761b.put(v$d$d$a$b$c.class, a_m);
        eVar.c.remove(v$d$d$a$b$c.class);
        eVar.f1761b.put(o.class, a_m);
        eVar.c.remove(o.class);
        a$j a_j = a$j.a;
        eVar.f1761b.put(v$d$d$a$b$a.class, a_j);
        eVar.c.remove(v$d$d$a$b$a.class);
        eVar.f1761b.put(m.class, a_j);
        eVar.c.remove(m.class);
        a$a a_a = a$a.a;
        eVar.f1761b.put(v$b.class, a_a);
        eVar.c.remove(v$b.class);
        eVar.f1761b.put(c.class, a_a);
        eVar.c.remove(c.class);
        a$p a_p = a$p.a;
        eVar.f1761b.put(v$d$d$b.class, a_p);
        eVar.c.remove(v$d$d$b.class);
        eVar.f1761b.put(r.class, a_p);
        eVar.c.remove(r.class);
        a$r a_r = a$r.a;
        eVar.f1761b.put(v$d$d$c.class, a_r);
        eVar.c.remove(v$d$d$c.class);
        eVar.f1761b.put(s.class, a_r);
        eVar.c.remove(s.class);
        a$c a_c = a$c.a;
        eVar.f1761b.put(v$c.class, a_c);
        eVar.c.remove(v$c.class);
        eVar.f1761b.put(d.class, a_c);
        eVar.c.remove(d.class);
        a$d a_d = a$d.a;
        eVar.f1761b.put(v$c$a.class, a_d);
        eVar.c.remove(v$c$a.class);
        eVar.f1761b.put(e.class, a_d);
        eVar.c.remove(e.class);
    }
}
