package com.discord.utilities.error;

/* JADX INFO: loaded from: classes2.dex */
public enum Error$Type {
    FORBIDDEN_CLOUD_FLARE,
    FORBIDDEN_DISCORD,
    INTERMITTENT_CLOUD_FLARE,
    DISCORD_REQUEST_ERROR,
    DISCORD_REQUEST_RESOURCE_NOT_FOUND,
    DISCORD_BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    REQUEST_TOO_LARGE,
    UNAUTHORIZED,
    DISCORD_REQUEST_ERROR_UNKNOWN,
    RATE_LIMITED,
    NETWORK,
    SSL,
    TIMEOUT,
    CAPTCHA_KNOWN_FAILURE,
    IMAGE_NOT_FOUND,
    AUTOMOD_MESSAGE_BLOCKED,
    OTHER
}
