package d0.e0.p.d;

import com.discord.models.domain.ModelAuditLogEntry;
import d0.e0.p.d.m0.c.n0;
import d0.e0.p.d.m0.e.b.b0.a$a;
import d0.e0.p.d.m0.i.g$f;
import java.util.Collection;
import java.util.List;
import java.util.Objects;
import kotlin.NoWhenBranchMatchedException;

/* JADX INFO: compiled from: KClassImpl.kt */
/* JADX INFO: loaded from: classes3.dex */
public final class h<T> extends i implements d0.e0.c<T>, z {
    public final c0$b<h<T>.h$a> m;
    public final Class<T> n;

    public h(Class<T> cls) {
        d0.z.d.m.checkNotNullParameter(cls, "jClass");
        this.n = cls;
        c0$b<h<T>.h$a> c0_bLazy = c0.lazy(new h$b(this));
        d0.z.d.m.checkNotNullExpressionValue(c0_bLazy, "ReflectProperties.lazy { Data() }");
        this.m = c0_bLazy;
    }

    public static final d0.e0.p.d.m0.g.a access$getClassId$p(h hVar) {
        Objects.requireNonNull(hVar);
        return f0.f3198b.mapJvmClassToKotlinClassId(hVar.getJClass());
    }

    public static final Void access$reportUnresolvedClass(h hVar) {
        d0.e0.p.d.m0.e.b.b0.a classHeader;
        Objects.requireNonNull(hVar);
        d0.e0.p.d.m0.c.k1.a.f fVarCreate = d0.e0.p.d.m0.c.k1.a.f.a.create(hVar.getJClass());
        a$a kind = (fVarCreate == null || (classHeader = fVarCreate.getClassHeader()) == null) ? null : classHeader.getKind();
        if (kind != null) {
            int iOrdinal = kind.ordinal();
            if (iOrdinal == 0) {
                StringBuilder sbU = b.d.b.a.a.U("Unknown class: ");
                sbU.append(hVar.getJClass());
                sbU.append(" (kind = ");
                sbU.append(kind);
                sbU.append(')');
                throw new a0(sbU.toString());
            }
            if (iOrdinal != 1) {
                if (iOrdinal != 2) {
                    if (iOrdinal == 3) {
                        StringBuilder sbX = b.d.b.a.a.X("This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection ", "library has no idea what declarations does it have. Please use Java reflection to inspect this class: ");
                        sbX.append(hVar.getJClass());
                        throw new UnsupportedOperationException(sbX.toString());
                    }
                    if (iOrdinal != 4 && iOrdinal != 5) {
                        throw new NoWhenBranchMatchedException();
                    }
                }
                StringBuilder sbX2 = b.d.b.a.a.X("Packages and file facades are not yet supported in Kotlin reflection. ", "Meanwhile please use Java reflection to inspect this class: ");
                sbX2.append(hVar.getJClass());
                throw new UnsupportedOperationException(sbX2.toString());
            }
        }
        StringBuilder sbU2 = b.d.b.a.a.U("Unresolved class: ");
        sbU2.append(hVar.getJClass());
        throw new a0(sbU2.toString());
    }

    public boolean equals(Object obj) {
        return (obj instanceof h) && d0.z.d.m.areEqual(d0.z.a.getJavaObjectType(this), d0.z.a.getJavaObjectType((d0.e0.c) obj));
    }

    @Override // d0.e0.p.d.i
    public Collection<d0.e0.p.d.m0.c.l> getConstructorDescriptors() {
        d0.e0.p.d.m0.c.e descriptor = getDescriptor();
        if (descriptor.getKind() == d0.e0.p.d.m0.c.f.INTERFACE || descriptor.getKind() == d0.e0.p.d.m0.c.f.OBJECT) {
            return d0.t.n.emptyList();
        }
        Collection<d0.e0.p.d.m0.c.d> constructors = descriptor.getConstructors();
        d0.z.d.m.checkNotNullExpressionValue(constructors, "descriptor.constructors");
        return constructors;
    }

    public final c0$b<h<T>.h$a> getData() {
        return this.m;
    }

    public d0.e0.p.d.m0.c.e getDescriptor() {
        return this.m.invoke().getDescriptor();
    }

    @Override // d0.e0.p.d.i
    public Collection<d0.e0.p.d.m0.c.x> getFunctions(d0.e0.p.d.m0.g.e eVar) {
        d0.z.d.m.checkNotNullParameter(eVar, ModelAuditLogEntry.CHANGE_KEY_NAME);
        d0.e0.p.d.m0.k.a0.i memberScope$kotlin_reflection = getMemberScope$kotlin_reflection();
        d0.e0.p.d.m0.d.b.d dVar = d0.e0.p.d.m0.d.b.d.FROM_REFLECTION;
        return d0.t.u.plus((Collection) memberScope$kotlin_reflection.getContributedFunctions(eVar, dVar), (Iterable) getStaticScope$kotlin_reflection().getContributedFunctions(eVar, dVar));
    }

    @Override // d0.z.d.e
    public Class<T> getJClass() {
        return this.n;
    }

    @Override // d0.e0.p.d.i
    public n0 getLocalProperty(int i) {
        Class<?> declaringClass;
        if (d0.z.d.m.areEqual(getJClass().getSimpleName(), "DefaultImpls") && (declaringClass = getJClass().getDeclaringClass()) != null && declaringClass.isInterface()) {
            d0.e0.c kotlinClass = d0.z.a.getKotlinClass(declaringClass);
            Objects.requireNonNull(kotlinClass, "null cannot be cast to non-null type kotlin.reflect.jvm.internal.KClassImpl<*>");
            return ((h) kotlinClass).getLocalProperty(i);
        }
        d0.e0.p.d.m0.c.e descriptor = getDescriptor();
        if (!(descriptor instanceof d0.e0.p.d.m0.l.b.e0.d)) {
            descriptor = null;
        }
        d0.e0.p.d.m0.l.b.e0.d dVar = (d0.e0.p.d.m0.l.b.e0.d) descriptor;
        if (dVar == null) {
            return null;
        }
        d0.e0.p.d.m0.f.c classProto = dVar.getClassProto();
        g$f<d0.e0.p.d.m0.f.c, List<d0.e0.p.d.m0.f.n>> g_f = d0.e0.p.d.m0.f.a0.a.j;
        d0.z.d.m.checkNotNullExpressionValue(g_f, "JvmProtoBuf.classLocalVariable");
        d0.e0.p.d.m0.f.n nVar = (d0.e0.p.d.m0.f.n) d0.e0.p.d.m0.f.z.e.getExtensionOrNull(classProto, g_f, i);
        if (nVar != null) {
            return (n0) j0.deserializeToDescriptor(getJClass(), nVar, dVar.getC().getNameResolver(), dVar.getC().getTypeTable(), dVar.getMetadataVersion(), h$c.j);
        }
        return null;
    }

    public final d0.e0.p.d.m0.k.a0.i getMemberScope$kotlin_reflection() {
        return getDescriptor().getDefaultType().getMemberScope();
    }

    @Override // d0.e0.c
    public T getObjectInstance() {
        return this.m.invoke().getObjectInstance();
    }

    @Override // d0.e0.p.d.i
    public Collection<n0> getProperties(d0.e0.p.d.m0.g.e eVar) {
        d0.z.d.m.checkNotNullParameter(eVar, ModelAuditLogEntry.CHANGE_KEY_NAME);
        d0.e0.p.d.m0.k.a0.i memberScope$kotlin_reflection = getMemberScope$kotlin_reflection();
        d0.e0.p.d.m0.d.b.d dVar = d0.e0.p.d.m0.d.b.d.FROM_REFLECTION;
        return d0.t.u.plus((Collection) memberScope$kotlin_reflection.getContributedVariables(eVar, dVar), (Iterable) getStaticScope$kotlin_reflection().getContributedVariables(eVar, dVar));
    }

    @Override // d0.e0.c
    public String getQualifiedName() {
        return this.m.invoke().getQualifiedName();
    }

    @Override // d0.e0.c
    public List<d0.e0.c<? extends T>> getSealedSubclasses() {
        return this.m.invoke().getSealedSubclasses();
    }

    @Override // d0.e0.c
    public String getSimpleName() {
        return this.m.invoke().getSimpleName();
    }

    public final d0.e0.p.d.m0.k.a0.i getStaticScope$kotlin_reflection() {
        d0.e0.p.d.m0.k.a0.i staticScope = getDescriptor().getStaticScope();
        d0.z.d.m.checkNotNullExpressionValue(staticScope, "descriptor.staticScope");
        return staticScope;
    }

    public int hashCode() {
        return d0.z.a.getJavaObjectType(this).hashCode();
    }

    public String toString() {
        String str;
        StringBuilder sbU = b.d.b.a.a.U("class ");
        d0.e0.p.d.m0.g.a aVarMapJvmClassToKotlinClassId = f0.f3198b.mapJvmClassToKotlinClassId(getJClass());
        d0.e0.p.d.m0.g.b packageFqName = aVarMapJvmClassToKotlinClassId.getPackageFqName();
        d0.z.d.m.checkNotNullExpressionValue(packageFqName, "classId.packageFqName");
        if (packageFqName.isRoot()) {
            str = "";
        } else {
            str = packageFqName.asString() + ".";
        }
        String strAsString = aVarMapJvmClassToKotlinClassId.getRelativeClassName().asString();
        d0.z.d.m.checkNotNullExpressionValue(strAsString, "classId.relativeClassName.asString()");
        sbU.append(str + d0.g0.t.replace$default(strAsString, '.', '$', false, 4, (Object) null));
        return sbU.toString();
    }
}
