package b.g.a.a;

/* JADX INFO: compiled from: JsonFormat.java */
/* JADX INFO: loaded from: classes3.dex */
public enum i$a {
    ACCEPT_SINGLE_VALUE_AS_ARRAY,
    ACCEPT_CASE_INSENSITIVE_PROPERTIES,
    ACCEPT_CASE_INSENSITIVE_VALUES,
    WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS,
    WRITE_DATES_WITH_ZONE_ID,
    WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED,
    WRITE_SORTED_MAP_ENTRIES,
    ADJUST_DATES_TO_CONTEXT_TIME_ZONE
}
