package com.discord.utilities;

import android.os.Parcel;
import com.discord.api.utcdatetime.UtcDateTime;
import d0.Standard2;
import d0.z.d.Intrinsics3;
import s.b.Parceler;

/* JADX INFO: renamed from: com.discord.utilities.UtcDateTimeParceler, reason: use source file name */
/* JADX INFO: compiled from: Parcelers.kt */
/* JADX INFO: loaded from: classes2.dex */
public final class Parcelers implements Parceler<UtcDateTime> {
    public static final Parcelers INSTANCE = new Parcelers();

    private Parcelers() {
    }

    /* JADX INFO: renamed from: newArray, reason: merged with bridge method [inline-methods] */
    public UtcDateTime[] m20newArray(int i) {
        Intrinsics3.checkNotNullParameter(this, "this");
        throw new Standard2("Generated by Android Extensions automatically");
    }

    /* JADX WARN: Can't rename method to resolve collision */
    @Override // s.b.Parceler
    public UtcDateTime create(Parcel parcel) {
        Intrinsics3.checkNotNullParameter(parcel, "parcel");
        return new UtcDateTime(parcel.readLong());
    }

    @Override // s.b.Parceler
    public void write(UtcDateTime utcDateTime, Parcel parcel, int i) {
        Intrinsics3.checkNotNullParameter(utcDateTime, "$this$write");
        Intrinsics3.checkNotNullParameter(parcel, "parcel");
        parcel.writeLong(utcDateTime.getDateTimeMillis());
    }
}
