package com.discord.utilities;

import android.os.Parcel;
import com.discord.api.utcdatetime.UtcDateTime;
import d0.j;
import d0.z.d.m;
import s.b.a;

/* JADX INFO: compiled from: Parcelers.kt */
/* JADX INFO: loaded from: classes2.dex */
public final class UtcDateTimeParceler implements a<UtcDateTime> {
    public static final UtcDateTimeParceler INSTANCE = new UtcDateTimeParceler();

    private UtcDateTimeParceler() {
    }

    @Override // s.b.a
    public /* bridge */ /* synthetic */ UtcDateTime create(Parcel parcel) {
        return create(parcel);
    }

    public UtcDateTime[] newArray(int i) {
        m.checkNotNullParameter(this, "this");
        throw new j("Generated by Android Extensions automatically");
    }

    @Override // s.b.a
    public /* bridge */ /* synthetic */ void write(UtcDateTime utcDateTime, Parcel parcel, int i) {
        write2(utcDateTime, parcel, i);
    }

    /* JADX WARN: Can't rename method to resolve collision */
    @Override // s.b.a
    public UtcDateTime create(Parcel parcel) {
        m.checkNotNullParameter(parcel, "parcel");
        return new UtcDateTime(parcel.readLong());
    }

    /* JADX INFO: renamed from: write, reason: avoid collision after fix types in other method */
    public void write2(UtcDateTime utcDateTime, Parcel parcel, int i) {
        m.checkNotNullParameter(utcDateTime, "$this$write");
        m.checkNotNullParameter(parcel, "parcel");
        parcel.writeLong(utcDateTime.getDateTimeMillis());
    }

    /* JADX INFO: renamed from: newArray, reason: collision with other method in class */
    public /* bridge */ /* synthetic */ Object[] m20newArray(int i) {
        return newArray(i);
    }
}
