package com.discord.utilities;

import android.os.Parcel;
import com.discord.api.utcdatetime.UtcDateTime;
import p507d0.C12111j;
import p507d0.p592z.p594d.C12238m;
import p659s.p667b.InterfaceC13171a;

/* JADX INFO: compiled from: Parcelers.kt */
/* JADX INFO: loaded from: classes2.dex */
public final class UtcDateTimeParceler implements InterfaceC13171a<UtcDateTime> {
    public static final UtcDateTimeParceler INSTANCE = new UtcDateTimeParceler();

    private UtcDateTimeParceler() {
    }

    /* JADX INFO: renamed from: newArray, reason: merged with bridge method [inline-methods] */
    public UtcDateTime[] m11397newArray(int i) {
        C12238m.checkNotNullParameter(this, "this");
        throw new C12111j("Generated by Android Extensions automatically");
    }

    /* JADX WARN: Can't rename method to resolve collision */
    @Override // p659s.p667b.InterfaceC13171a
    public UtcDateTime create(Parcel parcel) {
        C12238m.checkNotNullParameter(parcel, "parcel");
        return new UtcDateTime(parcel.readLong());
    }

    @Override // p659s.p667b.InterfaceC13171a
    public void write(UtcDateTime utcDateTime, Parcel parcel, int i) {
        C12238m.checkNotNullParameter(utcDateTime, "$this$write");
        C12238m.checkNotNullParameter(parcel, "parcel");
        parcel.writeLong(utcDateTime.getDateTimeMillis());
    }
}
